# Generated by Django 5.1.4 on 2025-02-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Teacher_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('T_Name', models.CharField(max_length=30)),
                ('Subject', models.CharField(max_length=10)),
                ('Email_ID', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
    ]
