# Generated by Django 5.1.4 on 2025-02-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Password',
            field=models.CharField(default='default_password', max_length=30),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Username',
            field=models.CharField(default='default_user', max_length=30),
        ),
    ]
