# Generated by Django 5.1.4 on 2025-02-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Trainer', models.CharField(max_length=30)),
                ('Duration', models.IntegerField()),
                ('Syllabus', models.CharField(max_length=100)),
                ('Fees', models.FloatField()),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
    ]
