# Generated by Django 5.1.4 on 2025-02-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Course', models.CharField(max_length=30)),
                ('Dob', models.DateField()),
                ('Emailid', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
